webview/win32.py
Windows 2003 breaks with the error global name 'FileNotFoundError' is not defined in combination with Python 2.7.11. Removing 'FileNotFoundError' in the except fixes this issue.
=> Fix for Windows 2003

webview/win32.py
This closes #20.
I fixed it by running `futurize -1 webview\win32.py -w` (see <http://python-future.org/>).
=> Fix py32_gen import on Python 3 

webview/__init__.py, webview/cocoa.py, webview/gtk.py, webview/qt.py, webview/win32.py
This adds load_string for the Gtk and Qt versions. Cocoa and Win32 versions throw NotImplementedErrors.
The added function has parameters:
`load_string(unicode_content, mime_type="text/html", encoding="utf-8", base_uri="")`
In the Gtk version, 'encoding' changes the encoding of the entire webview. This is not supported in Qt, but the parameter is passed in anyway (and ignored).
Example usage:
webview.load_string(u"日本")
webview.load_string("日本")`
If the string is not unicode in Python 2, it is converted for the user.
=> Add Gtk and Qt implementations of load_string.

webview/qt.py
This commit fixed an issue when trying to import PyQt5's QWebView modules which led 
to a false positive that 'PyQt5 was not found' on Linux systems, this is
due to the fact that QtWebKitWidgets has been deprecated in Qt 5.5 and
eventually removed in Qt 5.6 in
favour of QtWebEngineWidgets. There's an extensive guide in the Qt docs
on how to port an application that used the old QWebView to the new
QWebEngineView.
http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html
Linux Users who run Arch, Fedora or bleeding edge software generally
will be affected by this issue as they'll probably have a version of Qt that's
greater than 5.5
=> This commit fixed an issue when trying to import PyQt5

webview/gtk.py
Seems to be broken after the latest update. I was seeing this message every time I tried to run pywebview:
File "webview-test.py", line 2, in <module>
webview.create_window("It works jim", "http://flowrl.com")
File "/usr/lib/python3.5/site-packages/webview/__init__.py", line 160, in create_window
gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscreen, min_size, _webview_ready)
File "/usr/lib/python3.5/site-packages/webview/gtk.py", line 127, in create_window
browser = BrowserView(title, url, width, height, resizable, fullscreen, min_size, webview_ready)
File "/usr/lib/python3.5/site-packages/webview/gtk.py", line 62, in __init__
webview.load_uri(url)
NameError: name 'webview' is not defined
=> Fix gtk window

examples/flask_app/src/backend/main.py
http.client was called httplib in Python 2
=> Updated flask example to be Python 2 compatible

webview/gtk.py
On GTK when body with/height is set to 100% in CSS after increasing the window size one could not resize content back to smaller size. I showed it on videos.
[before change](http://tinypic.com/r/iojhxs/9)
[after change](http://tinypic.com/r/ip3w2b/9)
What was the motivation for the changed line to be `add_with_viewport` instead of just `add`?
=> Fix resizing width/height: 100% problem on GTK

README.md, setup.py, webview/__init__.py
See #62. This also uses ["install extras"](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to specify which "flavor" of pywebview to install. If the dependencies are already present, installation proceeds just as before.
=> Qt4/5 fallback for Macs with Qt and no PyObjC

webview/qt.py
Renamed _handle_get_current_url function to _handle_current_url in order to use qt version of webkit.  This fixes #85
=> This fixes no attribute '_handle_current_url' in qt.py

webview/cocoa.py
The WebKit webview in macOS does not automatically handle the Javascript
window.print method. This fix let pywebview handle the print event via
`WebUIDelegate`'s [`webView:printFrameView:`](https://developer.apple.com/reference/webkit/webuidelegate/1387787-webview?language=objc) method.
=> handle webview print requests in cocoa. fix #97

webview/cocoa.py
Prior to this commit, pressing the Delete key on the Mac keyboard caused
the WebView to navigate to the previous HTML page, which is undesirable
in a desktop application.
This fix makes use of the WebView's policyDelegate to refuse a back-
navigation actions if it was triggered by pressing the Delete key.
This is most convinient for two reasons:
1. We need not worry about Delete key press events that may occur
at other places (say inside text-fields).
2. Back navigation triggered explicitly via other means (like the
JavaScript history.back() method) can be allowed gracefully.
Note: attempts to capture the keypress via the WebView's keyDown method
fails because the parent NSWindow automatically assigns a subview called
WebHTMLView as the firstResponder to keyDown events, which handles …
=> Disable delete key back-navigation in Cocoa. Fixes #102.

webview/cocoa.py
Don't know if this fix is relevant to Pywebview. I implemented it
for my own app using Pywebview. Thought I would share.
Oh, and this is like a follow-up to PR #98.
=> Like Safari, remove default margins while printing

webview/cocoa.py
* Fix broken examples
- Thread called load_html too early. Adds delay, like in other examples.
* Close instance on calling destroy(), not quit app
* Give a title to the child windows
- With the current design, there is no way to explicitly set the title of
the child windows (JS cannot set the title of the windows it opens). Web
browsers normally use the page title as the title for pop-up windows, so 
we follow suit.
=> [Cocoa] Improve handling of instances, give a title to child windows, and fix destroy

webview/gtk.py
GLib throws an error when the background_color string is not in valid
hex format. This fix adds a format check using a regex like we did in
`cocoa.py`.
Also fix Python 3.x error: "Gtk.CssProvider.load_from_data TypeError:
Item 0: Must be number, not str" (which caused the build fail on Travis).
=> [GTK] Add hex color format check

webview/gtk.py
Changed the GTK implementation to use GObject threading and signal the main loop to do stuff instead of doing them directly.
This avoids segfault in threaded envoirments.
=> GTK threading problems fix

webview/winforms.py
Added .dll at the end of the file name. This fixes the error mentioned on #163
=> Fixes WebView not finding WebBrowserInterop (WinForms)

webview/winforms.py
a few days I had created an issues [toggle_fullscreen doesn't work as expected](https://github.com/r0x0r/pywebview/issues/232), and i had a try to fix this problem by myself. It seemed that no matter variable *self.is_fullscreen* is, variable *screen* is always expected to obtain
=> fix #232 : toggle_fullscreen doesn't work as expected

tests/util.py, webview/__init__.py, webview/cocoa.py, webview/gtk.py, webview/qt.py, webview/winforms.py
The master instance could have been closed when creating new windows, we
cannot rely on it to create the window for us. So we use an arbitary
running instance. This is the pattern followed for such scenarios on the
other platforms.
Closes #229, closes #230.
=> [All] Change window close behaviour so that it returns control back instead of terminating

tests/test_set_window_size.py, webview/__init__.py, webview/cocoa.py, webview/gtk.py, webview/qt.py, webview/win32.py, webview/winforms.py
Added set_window_size to api.
Added for all backends, tested on two of them
```
set_window_size(width, height, uid='master')
```
Tested Platforms:
- cocoa
- winforms
Untested platforms:
- win32
- gtk
- Qt
I wasn't able to test the win32, qtk, and Qt, so if someone wants to test those that would be great.
=> Set Window Size Functionality

webview/cef.py
shutil.rmtree is only supposed to take a directory argument according
to docs. Was resulting in an exception on window shutdown.
=> Use os.remove rather than shutil.rmtree to remove error.log on exit

docs/guide/api.md
Fixed typo for 'togle_fullscreen()' to 'toggle_fullscreen()'.
=> Fixed typo

webview/util.py
pytest throws a warning in util.py (you only see it if pytest results are not cached and/or you make a change to the file):
webview/util.py:138
.../pywebview/webview/util.py:138: DeprecationWarning: invalid escape sequence \s
pattern = '<%s(?:[\s]+[^>]*|)>'
This pull request marks pattern literal as raw string, which avoids the warning.
=> Fix for pytest warning about invalid escape sequence

webview/js/api.py, webview/util.py
Escaping line breaks in results of the python calls causes problems when result object contains strings with line breaks. What you get on js side is strings with '\n' as literal strings (a slash followed by letter n) instead of the special new-line character. This basically mangles the data being passed from python to js in an unrecoverable manner: js code has no way of knowing if it was meant to be the literal text or a special character.
json.dumps() already escapes everything that needs to be escaped and creates a valid string to be passed to the js side. JSON.parse() correctly reverses the data to it's original state. I don't think there is a need to mess with special characters here.
=> Don't escape line breaks in result of js_bridge_call

webview/platforms/qt.py
Running on Ubuntu 19.04 with PyQt5 5.13.0. When I close the main window I get a segmentation fault (tested it on multiple machines). You can easily recreate the problem with 
`PYWEBVIEW_GUI=qt
python examples/simple_browser.py`
When you close the window (via x in the top right corner) you will see 'Segmentation fault (core dumped)' in the terminal.
It maybe a Qt bug, but it prevents the execution of any code after webview.start() since python crashes hard. I found that hiding the main window before _app.exit() avoids the segfault. 
It's a workaround (not a fix). 
P.S. If an inspector window is open when you close main window, you get segfault even with this workaround.
=> Workaround for segmentation fault on closing the main window with Qt

webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
partially tackles #351 adding a `window.set_window_position(x, y)` implemented **only for gtk and qt** platforms, sorry, I am not a Mac or Windows and have no experience with `cocoa` or `winforms`.
Leaving here as base for someone else to implement the rest of platforms :)
=> [WIP] add move function

setup.py
Without this package, loading gtk fails with:
[pywebview] GTK cannot be loaded
File "/home/dan/Documents/pywebview_ws/pywebview/webview/guilib.py", line 16, in import_gtk
import webview.platforms.gtk as guilib
File "/home/dan/Documents/pywebview_ws/pywebview/webview/platforms/gtk.py", line 25, in <module>
import gi
ModuleNotFoundError: No module named 'gi'
=> Add missing dependency for GTK

webview/platforms/cocoa.py
Doing it after leads to a titlebar height gap at the top of full-height windows.
=> [Cocoa] Apply frameless masks before creating window

webview/util.py, webview/window.py
In order to support python2.7 change getfullargspec() to getargspec().
=> Support python2.7: change getfullargspec() to getargspec()

docs/contributing/development.md
"Create a virtual environment" had a letter missing from "install" in the line "pip install -e ."
=> Fixed typo in pip command

tests/run.sh
This breaks the build because the tests were already failing, the failure
was just being suppressed. Travis would only fail if the last pytest
invocation in run.sh had a non-zero exit code. It appears this has been
the case since 3.0.
=> Break Travis Linux tests in favor of the truth.

webview/platforms/cocoa.py
Quick fix to make up down left and right work on OSX.  To see if you have this problem, try moving left and right in the text box of the todos example.
=> Fixes arrow keys not responding in text input fields.

tests/test_js_api.py, webview/util.py
This fixes issue #629 by making it so that we only pick up attributes that are instance methods.
=> Only expose class instance methods as functions for the js API

webview/guilib.py
I noticed that the variable `KDE_FULL_SESSION` was being overridden. This simple change ensures that those in a KDE desktop environment will default to qt, and the order of preference suggested in #220 is maintained.
=> Fix KDE_FULL_SESSION not being used

webview/js/api.py, webview/platforms/cef.py, webview/platforms/mshtml.py, webview/util.py
Hello.
1) In `js/drag.py` there is a call `window.pywebview._bridge.call('moveWindow', [x, y], 'move');`.
Then, if an engine is 'mshtml'/'cef'/'qtwebkit' then `window.external.call(funcName, params, id);` is called in `js/api.py`.
With 'mshtml' that causes an error: `param` is an object of type 'System.__ComObject' and call `window.move(*param)` in `util.py` fails with exception:
```
COMException : Error HRESULT E_FAIL has been returned from a call to a COM component.
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.CustomMarshalers.EnumeratorViewOfEnumVariant.MoveNext()
at System.Collections.IEnumerator.MoveNext()
at Python.Runtime.Iterator.tp_iternext(IntPtr ob)
at window.pywebview._bridge.call …
```
=> js bridge serialization fixes and optimization

webview/platforms/winforms.py
Winforms save dialogs previously had `*.*` file type filtering hardcoded this in the `create_file_dialog` function, the requested file types were discarded. This could cause issues where the user would select the wrong file extension and the program would subsequently have to fix the file extension and reimplement the "does-this-already-exist" check.
The added code matches that in the open dialog section:
https://github.com/MarkusFF/pywebview/blob/3627e7ac1ca24398330288e548ad074012c76b98/webview/platforms/winforms.py#L510-L513
=> winforms: Implement file type filter on save dialog

webview/platforms/cocoa.py
This means the `windowShouldClose` function is correctly called.
Closes: #698
=> 'Use `performClose` when closing Cocoa windows.'

webview/__init__.py, webview/platforms/qt.py
Use an off-the-record QWebEngineProfile, instead of (unexpectedly) persisting cookies.
Related: #531
=> QtWebEngine: use OTR profile

webview/platforms/winforms.py
As discussed in [issue 720](https://github.com/r0x0r/pywebview/issues/720), using pywebview with pystray causes a crash. This is because pywebview calls `windll.user32.DestroyIcon(icon_handle)` regardless of whether an icon handle was actually returned by `windll.shell32.ExtractIconW`. This change just moves the DestroyIcon call to within the null check a few lines above, and fixes the issue.
=> Only call DestroyIcon if an icon handle was found - fixes #720

examples/localization.py, webview/__init__.py, webview/localization.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
This is a bit fiddly due to the `create_window` calls happening before the `webview.start` call, hence the need to update the localization object within the `_initialize` function.
This maintains support for the existing API, the alternative is to remove `localization` from `webview.start` entirely, but this would be a breaking change. Keen to hear your thoughts before proceeding with the other GUI frameworks!
Closes: #697
=> Localization per window

webview/platforms/cocoa.py
Currently prevents closing windows when confirm dialogue is enabled, this fixes that.
=> [Cocoa] fix check for should close window.

webview/platforms/edgechromium.py
Fix for window.load.html() not working #779 
Enable User Agent override #728
=> Fix window.load.html() in EdgeChromium

docs/guide/api.md
Hi, cool project!
This is a quick PR for a broken link I found in the documentation.
=> Fix typo in example link

webview/platforms/winforms.py
If we are trying to use "edgechromium" as GUI in webview.start(gui="edgechromium"), it requires a Microsoft webview2 runtime engine. But the error message doesn't show this & instead, it shows,
**[pywebview] [WinError 2] The system cannot find the file specified**
I have updated this error including the detail "Microsoft webview2 runtime engine is not found". Now it will looks like this,
**[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path: Computer\HKEY_LOCAL_MACHINE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}     ts\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}**
Signed-off-by: muthusaravanan <muthusaravanan@solitontech.com>
=> Updated the error message if Microsoft webview2 runtime is not found

webview/platforms/winforms.py
Microsoft has changed the way their WebView2 installers work - by default the runtime is installed without administrator privileges.  Registry paths are also changed (HKEY_CURRENT_USER instead of HKEY_LOCAL_MACHINE, and no separate paths for 64-bit operating systems).
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2030
I've tested my changes with Win10 21H2, both 32-bit and 64-bit.
=> Support non-elevated installations of WebView2

webview/platforms/qt.py
Qt window size trigger was not set to take the right amount of arguments:
```
js: ERROR Error: Uncaught (in promise): TypeError: BrowserView.window_size_trigger[int, int] signal has 2 argument(s) but 3 provided
...
File ".../webview/platforms/qt.py", line 553, in resize_
self.window_size_trigger.emit(width, height, fix_point)
TypeError: BrowserView.window_size_trigger[int, int] signal has 2 argument(s) but 3 provided
```
Now `window_size_trigger` has its third argument type added.
=> Fix signature for Qt window size trigger

docs/contributing/development.md, docs/guide/installation.md, setup.py, webview/guilib.py, webview/platforms/qt.py
1. replace pyqt5 with [qtpy](https://pypi.org/project/QtPy/) as abstraction layer in the code, people can freely choose pyqt5, pyside2, pyside6 as the backend
2. replace default pywebview[qt] backend from pyqt5(GPL) to pyside2(LGPL), the LGPL License is more commercial friendly
3. add qt engine support for Windows, people can distribute Qt's built-in Chromium engine, and without requires for users to install additional Webview2(100+MB)
for now [QtWebEngine/ChromiumVersions](https://wiki.qt.io/QtWebEngine/ChromiumVersions)
|PySide2&6|Qt Version|Chromium Version|
| ---------- | ---------- | -------------------|
|PySide6 6.2.3|6.2.0|90.0.4430.228|
|PySide2 5.15.2.1|5.15.2|83.0.4103.122|
=> replace pyqt5 with qtpy

docs/examples/events.md, docs/guide/api.md, examples/events.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/edgechromium.py, webview/platforms/edgehtml.py, webview/platforms/gtk.py, webview/platforms/mshtml.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
Put window events into its own namespace `window.events`. Old events are still supported with a deprecation warning. Old events will be eventually removed in 4.0
#845
=> #845 Refactor events

webview/platforms/cef.py
System: **Windows 10**
Python interpreter version: **3.8.10**
Deps versions:
```
cefpython3==66.1
proxy-tools==0.1.0
pycparser==2.21
pythonnet==2.5.2
```
1. Intall deps
```bash
pip install -r requirements.txt
pip install cefpython3==66.1
```
2. Write code
```python
import webview
def main():
window = webview.create_window('Woah dude!', html='<h1>Woah dude!<h1>')
webview.start(debug=True, gui='cef')
if __name__ == '__main__':
main()
```
3. Problem
```bash
> python .\scratch.py
[pywebview] Using WinForms / CEF
[0323/060225.058:ERROR:main_delegate.cc(710)] Could not load locale pak for en-US
[0323/060225.058:ERROR:main_delegate.cc(717)] Could not load cef.pak
[0323/060225.058:ERROR:main_delegate.cc(734)] Could not load cef_100_percent.pak
[0323/060225.058:ERROR:main_delegate.cc(743)] Could …
```
=> Fix resources paths for cef

webview/window.py
Javascript generated for asynchronous evaluate_js call returned an actual boolean instead of a JSON stringified boolean.
=> #904 #905 #906 Fix callback return value in async evaluate_js

docs/examples/minimize_window.md, docs/guide/api.md, docs/guide/interdomain.md, docs/guide/usage.md, webview/platforms/winforms.py, webview/wsgi.py
There are small typos in:
- docs/examples/minimize_window.md
- docs/guide/api.md
- docs/guide/interdomain.md
- docs/guide/usage.md
- webview/platforms/winforms.py
- webview/wsgi.py
Fixes:
- Should read `synchronously` rather than `syncronously`.
- Should read `programmatically` rather than `programmmatically`.
- Should read `overridden` rather than `overriden`.
- Should read `minimized` rather than `minimzed`.
- Should read `implementations` rather than `implementatins`.
- Should read `coordinates` rather than `cordinates`.
- Should read `communication` rather than `commmunication`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

webview/platforms/cocoa.py
View menu was being placed for application menu and application menu was being placed as an empty menu at the end of the bar. Now, view menu is created as first menu after application menu and application menu is placed int he correct position.
=> Fix placement of app and view menus for Cocoa bar menu

webview/platforms/cef.py
if a script is executed with an error, then further script execution gets stuck
=> fix evaluate invalid js for cef

webview/platforms/qt.py
Fixes #854. As a side effect, this means [a few harmless Qt options](https://doc.qt.io/qt-5/qapplication.html#QApplication) can be set with command line flags.
=> Remove 'Empty key passed' messages

examples/menu.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py
Certain functions would freeze the app when called from the menu because they were running on the main thread. Instead, call the functions from a thread.
Has been tested on Mac, needs to be tested on Linux and Windows. Can be tested by running `examples/menu.py` and selecting the menu option at *Test Menu > Random > File Dialog*. This should show a file dialog without freezing.
=> Run menu functions on thread

webview/platforms/winforms.py
This PR fixes the issue reported at https://github.com/r0x0r/pywebview/issues/433#issuecomment-622522261 for WinForms. The JS result semaphore is released, and `None` is returned from `evaluate_js`. This is modeled on what is done for the GTK platform.
=> [WinForms] Fix hang on window closing when JS evaluation is in progress

webview/__init__.py
The `__all__` method has a missing comma so concatenates two strings which breaks wildcard imports.
```python
>>> from webview import *
File "<stdin>", line 1, in <module>
AttributeError: module 'webview' has no attribute 'screensRouting'
```
=> Add comma to list on dunder all

webview/platforms/cocoa.py
Change 8c3b47b9533fe9d5980df15fcf2596603cfc461d was done to disable right-click context menus (for issue [#12](../../pywebview/issues/12)).  But currently on MacOS, the context menu can still be activated by ctrl-left-clicking.  I think maybe it used to be disabled in both cases, but the code was changed later, maybe because the original code used a method that's now deprecated?  (webView_contextMenuItemsForElement_defaultMenuItems_ was overridden to return nil, which clears/prevents the menu.)
The current code disables the menu by overriding WKWebView.rightMouseDown_ and does not call the super (unless `_debug['mode']` is true), which would normally activate the menu.
In addition to the fact that ctrl-left-clicking still activates the menu, a second problem I ran into is that …
=> Avoid control-left-click context menu on MacOS, also allow right-click events to reach javascript handlers

webview/platforms/cocoa.py
Fixes 2nd issue in [#996](../../pywebview/issues/996), allowing any key combinations _not_ handled by `performKeyEquivalent_()` to reach javascript event handlers.
=> Return False from performKeyEquivalent_ in unhandled cases.  Remove cursor workarounds.

examples/multiple_servers.py, webview/__init__.py, webview/window.py
Individual windows will now start a server only if their URL is a web app.
All other traffic goes to the global server.
Modified multiple_servers example to call start with http_server=True since the webapps will no longer cause the global server to be started. Also added some global server detection to the example so if http_server is set False the third window will correctly display that the global server is not started, instead of crashing.
=> Fix for multiple servers starting when not necessary.

webview/platforms/gtk.py
After the Soup library is updated to 3.0, other libraries still depend on the 2.4 version of Soup, but it imports the 3.0 Soup by default, which will cause the application to fail to start.
```
/usr/lib/python3.10/site-packages/webview/platforms/gtk.py:34: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Soup
[pywebview] GTK cannot be loaded
File "/usr/lib/python3.10/site-packages/gi/importer.py", line 142, in load_module
introspection_module = get_introspection_module(namespace)
File "/usr/lib/python3.10/site-packages/gi/module.py", line 257, in get_introspection_module
module = IntrospectionModule(namespace, …
```
=> [GTK] Require Soup 2.4 instead of 3.0 by default

webview/platforms/cocoa.py
On macOS versions prior to Mojave, setting `backspaceKeyNavigationEnabled` causes a crash because the key is not present.
This code was originally added in PR #294 (and this crash discussed in issue #210), but subsequently broken in b40511d. 
This change also switches from `Foundation.YES/NO` to `True/False` in two places for consistency with usage elsewhere.
Related: 'allowFileAccessFromFileURLs' was also protected with try/except prior to this change, but does not seem to actually need it.
=> Fix macOS crash: catch KeyError on `backspaceKeyNavigationEnabled`

tests/run.ps1
A minor edit to the PowerShell test runner script to only attempt to remove `__pycache__` if it exists, avoiding an error.
=> Fix running tests in PowerShell when `__pycache__` doesn't exist

webview/http.py
Bottle.py versions prior to 0.12.23 (the latest on PyPi as of Feb 2023) require stdout and stderr to exist when that package is imported, which is not the case on Windows when using pythonw.exe or PyInstaller >= 5.8.0.
This change is similar to the recently-merged PR #1038 that fixed #1029, but the fix in that PR only works if using bottle.py 0.13-dev, which is unlikely in most cases given that this version is not on PyPi (note that the fix it contains was committed over two years ago in January 2021).
This change uses a `TemporaryFile` instead of `DummyLogWriter` to resolve the issue. Fixes #1044.
=> Fix pywebview with PyInstaller or pythonw (caused by bottle.py)

examples/multiple_servers.py, webview/__init__.py
Fix bug where http_port was not being forwarded to the actual window constructor
when create_window was called.
Added examples to multiple_servers.py where webapps are started on specific ports.
=> Bug fix for issue #1060

webview/__init__.py
On Ubuntu 20, Python 3.11 with QT and GTK, when no menu is passed to the `webview.start()`, there is still an (ugly) menu bar being displayed:
With this small fix, the `guilib.set_app_menu(menu)` get executed only if there is actually a menu to show. Resulting in:
=> Hide menu bar when there is no menu

webview/platforms/winforms.py
refer to: [MessageBox.Show](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.messagebox.show?view=windowsdesktop-7.0#system-windows-forms-messagebox-show(system-string-system-string-system-windows-forms-messageboxbuttons-system-windows-forms-messageboxicon-system-windows-forms-messageboxdefaultbutton-system-windows-forms-messageboxoptions-system-string-system-windows-forms-helpnavigator-system-object))
=> Fix the title and message of the `create_confirmation_dialog` function reversed

docs/guide/api.md, examples/localhost_ssl.py, requirements.txt, ssl.py, webview/__init__.py, webview/http.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py
I merged w/ your new threaded adapter, but this doesn't use it in SSL mode (yet).
This *only* supports the GTK backend ATM.  (I'm traveling, don't have access to test anything else ATM.)  Will look into the API for the others later.  I intentionally left it so it will fail (as `add_tls_cert()` won't exist) if you try to use it with another backend. 
This is quite a bit bigger than I anticipated.  I'm not familiar w/ bottle's internals, there may be a better way to wrap the socket w/ bottle mixins.
https://github.com/r0x0r/pywebview/issues/1034
=> SSL support for internal server

webview/http.py
PR #1048 fixed #1044 by using `tempfile.TemporaryFile` on Windows when using pythonw.exe or PyInstaller >= 5.8.0, addressing an issue with bottle.py.
This worked, but in some cases (that unfortunately I cannot fully isolate) this can lead to a hang. This change switches methods to use `os.devnull` instead, which resolves the issue.
=> Switch from tempfile to os.devnull to fix PyInstaller issue

webview/platforms/cocoa.py
Crashed with `[pywebview] 'BrowserView' object has no attribute 'datastore'` before this fix.
=> Fix getting cookies in cocoa

webview/platforms/edgechromium.py, webview/platforms/winforms.py
This PR solves two bugs described in #1081.
an uninitialized list was checked for its length.
`_private_mode` is `True` by default. This causes `cache_dir` to be `None` by default in `winforms.py`
Webview2 crashes if no `UserDataFolder` exists.
To solve this issue, pythons `tempfile.TemporaryDirectory` is used to set `cache_dir` to a temporary directory.
Actually, I wanted to use `TemporaryDirectory` context manager to auto delete the created directory, after window is closed.
Unfortunately, the process still accesses some of the files and blocks the deletion process. A `sleep(1)` solves this issue, but that's a dirty solution.
=> Fix edgechromium cache

webview/platforms/edgechromium.py
Fixes #1118. Note that I have not attempted to create a mechanism to re-enable this feature through the `webview` interface, partly because it's platform-specific.
It may be interesting in the future to allow the user to pass arguments to `AdditionalBrowserArguments`, but a cross platform solution/mechanism presumably needs to be devised for that purpose. I'm not familiar enough with the Linux and Mac interfaces enough to determine whether adding a `window_args`  might make sense.
=> Disable touchpad elastic overscroll by default for Edge/Webview2 on Windows

README.md
Remove stated limit of Python 3.8 for Windows from Read Me. Python 3.9 and above have been supported on Windows since the release of pythonnet 3.
=> Remove stated limit of Python 3.8 for Windows from Read Me

docs/guide/api.md, webview/platforms/gtk.py
This simple fix allows users to prevent window closing from `closing` event handlers even if `confirm_close` is not set.
=> [GTK] Fix closing event handlers cancellation

docs/guide/api.md, webview/platforms/gtk.py
This is what I view as a complete fix for the closing event beahvior under GTK. I did a separate pull request from a smaller fix because I'm not sure this one is wanted: maybe the documentation is wrong and the code was right.
What this does is to actually run the `events.closing` handlers _before_ the closing confirmation (if `confirm_close` is set), as explained in the documentation (see issue #1178).
It also simplifies the GTK code by merging the `close_window` and `on_destroy` functions, in the spirit of how it is done in the Qt code.
Maybe the new merged function should rather be called `on_window_close` to match other event handlers. But that's not really for me to decide :).
-----
As a bonus, it also looks up the value of the `confirm_close` property on the pywebview window at …
=> [GTK] closing event working as documented

webview/platforms/gtk.py
This should fix issue #1063 (never solved despite being marked as 'complete').
After coming across this error in my own work, debugging to the source, and looking at GTK's source code for the relevant area, I found a solution. If the `global _app` variable is `run()` for a second time, then an assertion in GTK will be triggered. This assertion protects an application from having its arguments parsed more than one time and is necessary due to the way that GTK handles parsing arguments. 
https://github.com/GNOME/glib/blob/main/gio/gapplication.c#L493-L497
The solution to this is to create a new app every time `webview.start()` is called. Currently the app is created under the condition that it is `None` when `webview.start()` is called. Given that the app has already been run at least once, …
=> [GTK] SEGFAULT on Second 'webview.start()' Call

docs/guide/api.md, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py
This is a sibling PR to #1180, but update Qt, Cocoa, and Windows platforms in addition to GTK. The goal is to make the implementation follow the documentation which states that window closing event handlers are called before the closing confirmation dialog (in the case `confirm_close` is set).
I made it a separate PR because even though the changes are quite straightforward and should not cause any problems, _**I have not tested them**_. I do not have a Windows nor a Mac, and the Qt platform does not work for me (I'm using KDE but strangely, attempting to use Qt with pywebview fails, it only show a blank window, that's why I work using GTK).
So, these have to be tested by someone before they get merged!
Here is a simple test program:
```python
import time
import webview
prevent_closing = …
```
=> Update closing event behavior to match GTK behavior in PR #1180

webview/platforms/qt.py, webview/util.py
I don't know why, but it's a common solution for #890 (White screen displayed)
such as: 
- https://github.com/LCA-ActivityBrowser/activity-browser/pull/954
- https://bugs.archlinux.org/task/73957
- https://www.google.com/search?q=arch+rstudio+no+sandbox
And sometimes it needs two "--no-sandbox" flags
=> Add no sandbox for arch/manjaro/nixos to avoid white screen problem

webview/platforms/gtk.py
This simple change fixes the behavior I exposed in issue https://github.com/r0x0r/pywebview/issues/1177 by making the type returned by `create_file_dialog` alsways consistent (a tuple of file pathes).
=> Fix issue #1177

docs/guide/virtualenv.md
This change updates the dead link in the documentation related to virtuelenv as described in #1220.
=> Fix docs virtualenv link

.travis.yml, docs/guide/installation.md, webview/platforms/gtk.py
According to "WebKitGTK API for GTK 4 Is Now Stable" [1], webkit2gtk-4.0 is obsolete and users should immediately port to webkit2gtk-4.1. Besides, webkit2gtk-4.1 using GTK 3 and libsoup 3 has become the default API version in WebKitGTK 2.40 [2].
The GNOME 44(+) flatpak runtimes have already dropped webkit2gtk-4.0:
```
$ flatpak run --command=find org.gnome.Platform//44 /lib/x86_64-linux-gnu/ -name libwebkit*
/lib/x86_64-linux-gnu/webkitgtk-6.0/injected-bundle/libwebkitgtkinjectedbundle.so
/lib/x86_64-linux-gnu/libwebkitgtk-6.0.so.4
/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0.12.4
/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0
/lib/x86_64-linux-gnu/libwebkitgtk-6.0.so.4.4.4
/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so
```
PS. GNOME 43 flatpak runtime …
=> [GTK] Bump WebKit2 to 4.1

webview/platforms/edgechromium.py, webview/platforms/gtk.py, webview/platforms/qt.py
It enables access to `file://` paths when on `file://` loaded page. It does not allow to access `file://` when using remote or built-in http server.
For supported platforms, QT - going by their docs - seems to enable it by default and Cocoa has in enabled explicitly. Seems that only GTK and Edge are omitted.
I'm not sure if it would be better to have it as an option, but then if defaulted to False things could stop working for people on Mac and QT. So enabling it at least should give same behavior everywhere.
Similar (same?) to https://github.com/r0x0r/pywebview/issues/1013.
=> Enable access to local-files when using file:// uris on omitted platforms.

appveyor.yml, webview/platforms/gtk.py
Some Linux OS versions have not included WekKit 4.1, such as Ubuntu 20.04. Fix the Webkit 4.0 and Soup 2.4 as the fallback.
Fixes commit 34432a3bc8a3 ("[GTK] Fallback for Webkit4.1")
=> [GTK] Fix WebKit 4.0 as fallback

webview/platforms/cocoa.py
Later versions of MacOS give the warning:
```
WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```
This commit adds the method to address this warning.
=> add method to prevent secure coding WARNING on cocoa

tests/test_multi_window.py, tests/test_vibrancy.py
The original test_multi_window.py tries to load the web page rendering with the GBM device. But, it shows the error and blocks test:
```
test_multi_window.py
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0 rootdir: /home/dev/pywebview/tests
collected 5 items
test_multi_window.py ..Unable to access the GBM device, disabling DMABuf video sink. [pywebview] Main window failed to start
File "/home/dev/pywebview/tests/util.py", line 72, in thread
thread_func(window)
File "/home/dev/pywebview/tests/test_multi_window.py", line 110, in load_url
child_window.destroy()
File "/home/dev/pywebview/webview/window.py", line 45, in wrapper
raise …
```
=> Avoid test a web page needing GBM device

appveyor.yml
The original appveyor matrix uses two Ubuntu2004 images to test QT and GTK platforms. But, that might confuse the runner and always test QT platform. So, change GTK platform runner's image to Ubuntu2204.
=> [appveyor] Use Ubuntu 22.04 to test GTK platform

appveyor.yml
The Xvfb places the display server with number 99. So, set DISPLAY environment variable as ":99". Then, GTK tests can render on it.
=> [appveyor] Set display number to enable GTK test

appveyor.yml
The QT version test always fails at "OpenGL context creation":
```
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed. Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) [3:3:0100/000000.882327:ERROR:zygote_linux.cc(614)] Zygote could not fork: process_type renderer numfds 3 child_pid -1 [3:3:0100/000000.882527:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
./run.sh: line 10:  8703 Aborted …
```
=> [appveyor] Set display number to enable QT test

examples/js_api.py, tests/test_js_api.py, webview/js/api.py, webview/util.py
This PR introduces nested API definitions. Previously, only methods defined on the base API class instance were available on the frontend. The new structure allows for a more organized, readable, and scalable approach by grouping related functionalities into separate classes.
**Example Usage**:
```python
class MathAPI:
@classmethod
def add(cls, a: int, b: int):
return a + b
@classmethod
def subtract(cls, a: int, b: int):
return a - b
class GreetingAPI:
@classmethod
def greet(cls, name: str):
return f"Hello, {name}!"
class RootAPI:
math = MathAPI
greetings = GreetingAPI
@classmethod
def ping(cls):
return "pong"
if __name__ == '__main__':
window = webview.create_window('JS API example', html=html, js_api=RootAPI)
webview.start()
```
With this structure, the APIs can be accessed in …
=> Support for nested API definitions

webview/__init__.py
Nothing major, just noticed that the `html` param for the `create_window` function was missing. Feel free to edit.
=> Added missing param to doc

docs/guide/usage.md
I believe this to be a mistake in the docs, the correct call seems to be either `webview.create_window('Woah dude!', 'src/index.html')` or `webview.create_window('Woah dude!', url='src/index.html')`
=> Fix example code in usage.md (using html param, but parameter is file url)

webview/platforms/gtk.py
Set the policy of the `Gtk.ScrolledWindow()` to `Gtk.PolicyType.NEVER`.
Fixes #1332
=> Set `ScrolledWindow` policy to `NEVER`

webview/platforms/qt.py
This simple example just showed a blank/white screen, even after installing the dependencies:
```py
import webview
webview.create_window('Hello world', html = '<h1>Hello world</h1>')
webview.start(debug = True)
```
The logs didn't help as it didn't show anything more than:
```console
$ PYWEBVIEW_LOG=debug PYWEBVIEW_GUI=qt python test.py
[pywebview] Using Qt 5.15.2
DevTools listening on ws://127.0.0.1:8228/devtools/browser/43d54d29-4157-44fa-ad66-2200c783fa29
<PyQt5.QtWebEngineWidgets.QWebEngineProfile object at 0x7d20c5fe3910>
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:8228
```
Then I searched through the issues and came across to this https://github.com/r0x0r/pywebview/issues/1325#issuecomment-1981757261 and this PR #1189,
And …
=> Fix for blank screen with QT in Pop!_OS (no-sandbox flag)

examples/todos/buildozer.spec
1.fixed the error "clang-14: error: no such file or directory: 'todos/arm64-v8a'", the buildozer package.name requirement is one word with only ASCII characters and/or numbers. It should not contain any special characters
2.fix the error "if exclude_dir[-1] != '/':IndexError: string index out of range" while "buildozer -v android release"
=> fix 2 errors while "buildozer -v android debug deploy run"

webview/dom/dom.py
`escape_quotes` is inadequate here, as it will happily leave multiline strings as they are, which is a syntax error in javascript. It also doesn't seem to adequately deal with things like existing backslash escapes in the string.
`json.dumps` is guaranteed to produce valid json, which is also guaranteed to be a valid javascript data structure. By ensuring the type of `html` to be `str`, we guarantee that the output of `json.dumps` will be a valid javascript string, properly quoted and escaped.
=> Replace `escape_quotes` with `json.dumps` in `DOM.create_element`

pyproject.toml, requirements.txt, webview/http.py, webview/platforms/cocoa.py
`SSLContext().wrap_socket()` has been recommended over `ssl.wrap_socket()` since python 3.2.
`ssl.wrap_socket()` has been deprecated since python 3.7 and has been removed in 3.12.
Also add a missing Darwin dependency (`pyobjc-framework-Quartz`) and fix a bug where the Cocoa app main menu keeps acquiring duplicate default items on every call to `BrowserView.first_show()`.
=> Replace `ssl.wrap_socket` with `SSLContext(...).wrap_socket()`

webview/platforms/winforms.py
the shcore dll is not present on Windows 7, this adds an exception handler for this case
=> [winforms] fix: windows 7 compatibility

webview/platforms/edgechromium.py
After building a project using PyInstaller into a single executable file, during the application's runtime, a folder named "exe.WebView2" was created next to the executable file. Due to the location of the executable, the application lacked the necessary permissions to modify its folder, leading to runtime issues.
Attempts to resolve this issue by following the suggestions mentioned in [this discussion](https://github.com/r0x0r/pywebview/issues/1037#issuecomment-1424732083) did not yield the desired results.
Upon consulting the WebView2 documentation, specifically the "Manage user data folders" section [(source)](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=dotnet), I discovered that it's possible to specify a custom path for the creation of the …
=> fix: Set WebView2 user data path

docs/guide/freezing.md
For some reasons - maybe Github's internal CDN design, the file "pretty" URL isn't enough to access the resource in GitHub when used from external sources. Permalink surely does.  The original link was working from within GitHub but not when it was clicked from PyWebView documentation.
=> Replaced internal URL with permalink

webview/platforms/cocoa.py
44033b8589e462017f097b6274094fee4945647c added a call to [`abortModal()`](https://developer.apple.com/documentation/appkit/nsapplication/1428753-abortmodal), but with an extra `_` that means the call fails and prints `<class 'AttributeError'>: 'NSApplication' object has no attribute 'abortModal_'` on every exit. This commit removes the underscore.
=> Fix `abortModal` call

examples/window_title_change.py
Since the thread running the timer loop in `examples/window_title_change.py` is not a daemon thread, the program will not exit when the main thread ends due to the window closing.
Instead of using an uninterruptible sleep, we can use the window closed event as the timer with the added bonus that we can exit the timer loop when the window is closed so that the program can exit.
=> Fix window change title example exit

docs/guide/api.md, examples/remote_debugging.py, webview/__init__.py, webview/platforms/edgechromium.py
Allow configuring the Chromium remote debugging port via `webview.settings`. This makes it possible write tests for the application using Playwright via this guide: https://playwright.dev/docs/webview2
=> Allow configuring Chromium remote debugging port

webview/menu.py
This pull request includes changes to the `webview/menu.py` file to fix type annotations.
Changes:
* [`webview/menu.py`](diffhunk://#diff-9d70e0c5c34ec7abc473ffce69d2af75c077c04318ae94332537380b2fd553f2L7-R8): Updated the `Menu` class initializer to accept a list of items that can be `Menu`, `MenuAction`, or `MenuSeparator` instead of `str`.
* [`webview/menu.py`](diffhunk://#diff-9d70e0c5c34ec7abc473ffce69d2af75c077c04318ae94332537380b2fd553f2L18-R19): Modified the `MenuAction` class initializer to allow the `function` argument to return any type instead of `None`.
=> Correct `Menu` typing

tests/test_download.py, webview/platforms/cocoa.py
The download attribute wasn't forcing a download on mac, this makes it do that, and respects the suggested filename!
Also add a test but skip it since it needs to be run manually and have user confirmation. Test fails before change and passes after.
=> Add support for the download attribute on links for Cocoa/MacOS platform

webview/platforms/cocoa.py
A previous commit had moved `get_active_window` into `BrowserView` in `cocoa.py` when it needed to be outside. This caused `get_active_window` to fail on Cocoa. This fix just moves the function back outside.
=> Fix Cocoa `get_active_window`

webview/platforms/cocoa.py
[Cocoa] Fix location that new subviews get added
Y axis is flipped for the web coordinate system vs. the window, so events originating from the webview will have flipped coordinates
Resolves #1568
=> [Cocoa] Fix location that new subviews get added

webview/platforms/winforms.py
In the latest github version, the user cache will be cleaned before closing the window, which will cause a short window blank phenomenon when closing the window. My modification method is to hide the window immediately when clicking the window button, and then perform cache cleanup and process termination in the background, so as to indirectly fix the window blank problem and improve the user experience.
=> Fix a short blank when closing the window

webview/platforms/cocoa.py
On Mac when quitting with Cmd+Q, the `closing` event and `confirm_close` dialog responses were being ignored, causing the app to quit even after the user said they don't want it to. This small change will keep the app running if any of the windows indicate they shouldn't be closed.
=> [Cocoa] Don't terminate app if windows shouldn't close

docs/guide/api.md, docs/guide/interdomain.md, docs/guide/usage.md
1. I noticed two places in docs where the link to renderer is broken.
2. Also a typo in docs/guide/interdomain.md
1. Navigate to https://pywebview.flowrl.com/guide/usage.html#basics
2. Click: See [Renderer](https://pywebview.flowrl.com/guide/renderer.html) for details
Another place
1. Navigate to https://pywebview.flowrl.com/guide/api.html#webview-start
2. Click See [Renderer](https://pywebview.flowrl.com/guide/renderer.html) for details.
I tried to fix it by linking to `web_engine.md`.
=> Update docs: fix broken link to renderer and a typo

webview/platforms/android.py
This PR enables fullscreen support on Android as discussed in #1598
=> Add fullscreen support to android

webview/http.py
I was about to open an issue but then I thought i would just fix it and move on
BottleServer class was determining server root wrong when multiple local-url windows were created:
I.E: creating two local-url windows pointing to files as follows:
**'C:/projects/web/index.html'**
**'C:/projects/web/splash.html'**
will set server root to **'C:/projects'** instead of **'C:/projects/web'**
@ http.py - line 100 ->
`os.path.dirname(os.path.commonpath(local_urls)) if len(local_urls) > 0 else None`
For most cases, `os.path.commonpath()` already returns the required path (**'C:/projects/web'** in the example), using `os.path.dirname()` on it just make it go up another level, causing the issue
check if `os.path.commonpath()` already returned a dir and use that one if so, otherwise pass it trough …
=> [BUGFIX] multiwindow with local-url setups sets wrong server root (BottleServer)

webview/platforms/winforms.py
In `winforms.py`, the `create_file_dialog` function returns a string value that is not of type `Sequence[str] | None` when saving a file, which is inconsistent with its function signature.
https://github.com/r0x0r/pywebview/blob/02daa3ad41821a900b5c7e9bf5bec9d53614667a/webview/window.py#L502-L510
The issue comes from:
https://github.com/r0x0r/pywebview/blob/02daa3ad41821a900b5c7e9bf5bec9d53614667a/webview/platforms/winforms.py#L798
=> create_file_dialog should return Sequence[str]

webview/platforms/cocoa.py
👋 noticed that `OPEN_DEVTOOLS_IN_DEBUG` wasn't taking effect on Cocoa unlike other GUIs like edgechromium and qt. Took a stab at implementing it, albeit with some private APIs which may or may not work - didn't see any public options available. This worked for me on macOS 15.4.1.
I'm a bit out of my depth here, but some AI assistance nudged that there could be some other possible fallback implementations as well:
```py
try:
import objc
_WKInspector = objc.lookUpClass('_WKInspector')
if _WKInspector:
inspector = _WKInspector.alloc()
if hasattr(inspector, 'show'):
inspector.show()
return True
except:
pass
try:
if hasattr(webview, 'performSelector_'):
selector_name = objc.selector(b'_showInspector', signature=b'v@:')
webview.performSelector_(selector_name)
return True
except:
pass
```
I left …
=> [Cocoa] Implement `OPEN_DEVTOOLS_IN_DEBUG`

webview/__init__.py, webview/window.py
1. When using a WSGI app (such as Flask, etc.), it is impossible to enable the default SSL certificate generate.  
2. When the user specifies server_args, the content specified by the user will be given priority.
=> Fix the issue of specifying server_args for SSL

webview/guilib.py
I noticed that the `GUIType` type does not include all valid GUIs like `cocoa`. Within pywebview source this isn't an issue since Darwin logic often just defaults to Cocoa:
https://github.com/r0x0r/pywebview/blob/d018f1d87a08d90c4d11211881037d6e51a19e96/webview/guilib.py#L103-L107
However, I noticed this issue in userland writing my own logic involving `GUIType`. For consistently, it would be nice to include all valid targets.
Similarly, I also noticed that parsing logic for `PYWEBVIEW_GUI` only checks a handful of GUIs. I'm assuming this was accidental and fixed, though if we intentionally only want to support overrides for a handful of GUIs I can revert that change.
=> Add `cocoa` to `GUIType`, accept all GUIs in `PYWEBVIEW_GUI` env var
