r0x0r/pywebview

webview/cocoa.py
Allows Mac apps created with `pywebview` and packaged with `py2app` to follow the customary pattern of showing an application menu when the app name is clicked in the top menu bar. The new menu items are:
* Services
* _-----------------------_
* Hide _[App Name]_
* Hide Others
* Show All
* _-----------------------_
* Quit _[App Name]_
The _[App Name]_ will only show in some menu items if `CFBundleName` is available in the bundle's `infoDictionary`. Otherwise it will be omitted.
The functionality for adding the menu and appending the app name were implemented as private methods to the `BrowserView` class so they don't change its public API.
I've also included a screenshot of the resulting menu on a dummy application bundled with `py2app`:
Fixes #35.
=> Add default Cocoa application menu for Mac apps. Fixes #35.

webview/cocoa.py
May close r0x0r/pywebview#45
Advanced About dialog functionality can be found [here].(http://cocoadevcentral.com/articles/000071.php)
=> Added a standard Mac OS About menu

webview/cocoa.py
May close r0x0r/pywebview#52
The system shortcut key is `Control-Command-F`.
=> Added a View menu to enable the system Full Screen shortcut key

webview/cocoa.py, webview/localization.py
A very basic solution. Follow up to #98
=> handle javascript alert method in cocoa

webview/cocoa.py
Also added an example script.
We use another webview as the placeholder till the webview is loaded.
Param background_color and loading_image become the CSS background-color
and background-image of the webview's <body> respectively. This is the
easiest hack that is also portable across platfroms. :)
=> [Cocoa] Add background color 

webview/gtk.py
Tested `loading_animation.py`. No white-screen delay.
=> [GTK] Add background color

README.md
updated clr hook info for Pyinstaller when using WinForms and pythonnet dependencies
=> updated clr hook info

webview/cocoa.py
Display an open file dialog when an `<input type="file">` HTML element is
clicked. Solves #116 on Mac.
=> [Cocoa] Implement support for file input control

webview/cocoa.py, webview/localization.py
=> [Cocoa] Implement JavaScript confirm method

webview/__init__.py, webview/cocoa.py, webview/gtk.py, webview/qt.py, webview/winforms.py
=> Fix subthread deadlocks when closing the window

webview/cocoa.py
This makes choosing between multiple file filters similar to that on
other platforms.
See https://github.com/r0x0r/pywebview/issues/139#issuecomment-345433587.
=> [Cocoa] Add file filter menu to create_file_dialog

README.md, examples/window_title_change.py, tests/conftest.py, tests/test_set_title.py, tests/util.py, webview/__init__.py, webview/cocoa.py, webview/gtk.py, webview/qt.py, webview/winforms.py
+ Fix a js_bridge exception on GTK
+ Bonus refactoring
=>  #159 Implementation of set_title() function

webview/qt.py
please check lines 146 and 294, probably you really want to use > instead of >=
and line 252 and 301 probably most to be >= instead of >
I am not familiar with Qt so I can't guess, any way I will investigate about it if I have time.
=> fixed some problems with PyQt versions

webview/js/api.js, webview/qt.py
With this fix all remaining Travis test fails would boil down to the `assert_js`
function (#128).
=> Partially fix Travis CI tests

examples/load_html.py, webview/__init__.py, webview/cocoa.py, webview/gtk.py, webview/qt.py, webview/win32.py, webview/winforms.py
=> #178 Remove base_uri parameter from the load_html function

setup.py
this should fix the JS folder not loading. Its tested on linux and mac. sorry I don't a PC that  I could test it on
Jose
=> Fixed js not importing issue

webview/__init__.py
Rewrote the original #207 to use decorators.
=> [All] Refactor API calls to remove duplicate code

README.md
=> Typo :beers:

README.md, examples/qt_test.py, webview/__init__.py, webview/qt.py
+ Fix import logic 
+ Introduce PYWEBVIEW_FORCE_GUI environment variable
=> #220: Refactor import logic

README.md
I added csrf warnings, as I'd raised an issue for earlier.
=> added csrf warnings

CHANGELOG.md, setup.py
Get rid of extras and assume a GUI framework instead
=> Simplify installation

docs/examples/js_api.md, examples/js_api.py
this is my contribution to issue #288
=> Added an example how to use the js_api with parameters.

appveyor.yml
Bump pytest version to avoid crash.
=> Bump PyTest to Fix CI

examples/js_api.py, package-lock.json, package.json, webview/js/api.py, webview/util.py
=> JS API exception handling

docs/examples/change_url.md, docs/examples/destroy_window.md, docs/examples/events.md, docs/examples/get_current_url.md, docs/examples/get_elements.md, docs/examples/links.md, docs/examples/loading_animation.md, docs/examples/multiple_windows.md, docs/examples/open_file_dialog.md, docs/examples/save_file_dialog.md, docs/examples/toggle_fullscreen.md, docs/examples/window_title_change.md
Hi, I removed unnecessary imports from examples.
=> Removed unnecessary imports

docs/.vuepress/config.js, docs/examples/move_window.md, docs/guide/api.md, examples/move_window.py, webview/__init__.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
Addresses #351. Adds an ability to specify window coordinates on start, as well as move window programmatically.
=> Move window

docs/.vuepress/config.js, docs/examples/hide_window.md, docs/guide/api.md, examples/hide_window.py, tests/run.ps1, tests/test_hide_window.py, tests/test_http_server.py, webview/__init__.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
+ a new param `hidden` of `create_window`
Addresses #253
=> Hide / show window methods

tests/run.ps1, webview/platforms/cef.py
This PR fixes a deadlock that is caused by window.pywebview not being ready after loaded event is set.
=> CEF deadlock fix

webview/http_server.py, webview/js/api.py, webview/js/event.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/winforms.py, webview/util.py
=> [CEF] Set high DPI mode

docs/examples/events.md, docs/guide/api.md, examples/events.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
Introduce two new events: closed and closing. #381
=> Implement close events

webview/platforms/qt.py
=> Enable microphone/webcam for qt only (QtWebEngine/Chromium) (#403)

webview/platforms/qt.py
=> defaulted debug port to 8228 in Qt

README.md
Without webview.start() it does nothing
=> Fixed the Hello world code

webview/event.py
=> Catch exceptions in event handlers

webview/platforms/cocoa.py
=> Fix simple typo: transfor -> transfer

webview/platforms/cef.py
=> added command line switches dict to allow webcam usage and more command line configurations in cef

README.md, webview/__init__.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/window.py
Issue #488
Tested working on Linux Qt and Gtk.  Needs more work for the `cef`, `cocoa`, and `winforms` platforms.
=> Added basic support for transparent windows

webview/event.py
https://github.com/r0x0r/pywebview/issues/528
=> 528: Loaded event fix

webview/platforms/gtk.py
=> Fix for issue #576

docs/guide/README.md
I have been away from this project too long to still qualify as a maintainer. I shall continue to contribute as and when possible. @r0x0r
=> Remove maintainer (myself)

webview/platforms/cocoa.py
Adds support for `cmd+w` to close window on MacOS.
=> Add support for cmd+w on MacOS to close the current window.

setup.py
Closes: https://github.com/r0x0r/pywebview/issues/511
=> Only install the specific `pyobjc` packages required.

webview/platforms/edgehtml.py, webview/platforms/winforms.py
Update **edgehtml** `evaluate_js` function to handle concurrent or consecutive scripts more reliably.
=> Update edgehtml evaluate_js function

docs/guide/api.md, webview/__init__.py
Resolves #639. I also changed the signature in `api.md` to match the function signature.
=> Add docs for start method

.travis.yml, appveyor.yml, docs/.vuepress/config.js, docs/examples/screens.md, docs/guide/api.md, examples/screens.py, setup.py, tests/test_screens.py, webview/__init__.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/screen.py, webview/util.py
https://github.com/r0x0r/pywebview/issues/702
Implement `webview.screens` property.
This PR introduces a new dependency.
`pip install proxy_tools`
=> webview.screens

webview/__init__.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/edgechromium.py, webview/platforms/edgehtml.py, webview/platforms/gtk.py, webview/platforms/mshtml.py, webview/platforms/qt.py, webview/platforms/winforms.py
Change _debug to dict, so that its state preserves across modules. Fixes #628 .
=> Refactor debug logic

webview/platforms/edgechromium.py
console and alert in edgechromium is well fixed, now you can use devtool.
=> Delete the hack of edgechromium's console and alert

webview/platforms/cef.py
resolves issue https://github.com/r0x0r/pywebview/issues/806
=> add ability to set browser settings to cef

docs/examples/events.md, docs/guide/api.md, examples/events.py, webview/platforms/cocoa.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
Following events are implemented
on_minimized
on_restored
on_maximized
=> #828 Implement window management events

docs/guide/api.md, examples/evaluate_js_async.py, webview/js/api.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/edgechromium.py, webview/platforms/winforms.py, webview/util.py, webview/window.py
Add async support to evaluate_js
=> #801 Evaluate js async

docs/examples/events.md, docs/guide/api.md, examples/events.py, webview/event.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/edgechromium.py, webview/platforms/edgehtml.py, webview/platforms/gtk.py, webview/platforms/mshtml.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/window.py
=> Resize event

examples/assets/cookies.html, examples/cookies.py, webview/__init__.py, webview/http.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/edgechromium.py, webview/platforms/gtk.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/util.py
Add `start(private_mode=False)` parameter to support incognito mode
=> #531 Incognito mode and cookie support

webview/platforms/winforms.py
https://github.com/r0x0r/pywebview/issues/879
=> fix: Fix the problem with comparing webView versions when version is 100.0.xxx

webview/platforms/qt.py
Fixes issues with QT engine when using PySide6 or PyQt6. See #912 
- Error when centering window
- Error creating context menu
- JavaScript results not returned
- Disk Cache is disabled when using default profile
=> Update PySide6, PyQt6 backend

docs/guide/api.md
I initially Created a commit for this issue but closed it because i wasn't doing it right so please pardon me for that
The drag area message was a bit unclear on how to proceed in adding this class. Personally it took me a while to understand the class needs to be added in html. I have clarified the issued and showed an example case on how to use the drag area
=> docs: modified the Drag area explanation [Not duplicate]

docs/examples/change_url.md
=> docs: fix typo

webview/platforms/cocoa.py
Sorry for starting another PR. Forked the current version of pywebview. Should be easy to merge.
=> non-QUERTY keyboard shortcuts

webview/http.py, webview/util.py
Fix crashing when packaged with Pyinstaller
=> Pyinstaller fix

webview/platforms/qt.py
=> [QT] Fix user_agent

webview/platforms/qt.py
According to the discussion:
https://github.com/r0x0r/pywebview/discussions/1266
=> solve the blank main window issue with PyQt5 on RHEL9.

webview/platforms/winforms.py
=> fix Windows webview2 getting focus event triggered multiple times

webview/__init__.py, webview/platforms/winforms.py, webview/window.py
add frameless_border to get improved borderless window (shadows and Windows 11 rounded edges) #1310
=> add frameless_border to get improved borderless window (shadows and Windows 11 rounded edges) #1310

README.md, SECURITY.md
=> Minor README.md and SECURITY.md improvements

docs/guide/freezing.md
=> Nuitka @ the docs

webview/platforms/qt.py
=> Fix devtools in PySide6

webview/platforms/winforms.py
Fix FolderBrowserDialog changed to modern VistaDialog. The issue address is [no.1378](https://github.com/r0x0r/pywebview/issues/1378)
=> Fix FolderBrowserDialog changed to modern VistaDialog

webview/platforms/edgechromium.py
feat: implement initialization of WebView2 environment ﻿
- Added initialization logic for the WebView2 environment in the EdgeChrome class.
- Utilized CoreWebView2Environment.CreateAsync() to asynchronously create the environment.
- Implemented a callback function to ensure the WebView2 control is synchronized with the newly created environment.
=> feat: implement initialization of WebView2 environment ﻿

webview/js/api.py, webview/platforms/edgechromium.py, webview/util.py
1. Fix performance issues with the drag-and-drop (dnd) event.
2. Fix the exception caused by `args.get_AdditionalObjects()` being None in certain cases.
3. Fix the Edge URL bug.
4. Fix the bug where the full path cannot be retrieved when dragging a file with Chinese or other Unicode characters.
1. 修复dnd事件性能问题，
2. 修复某些情况下`args.get_AdditionalObjects()`为None导致的异常 
3.修复Edge URL BUG
4.修复拖动文件为中文等Unicode字符时，无法获取完整路径的BUG
=> fixed some issues

docs/guide/installation.md
=> Add missing `care` in `take care`.

webview/__init__.py, webview/http.py, webview/platforms/android.py, webview/platforms/cef.py, webview/platforms/cocoa.py, webview/platforms/edgechromium.py, webview/platforms/gtk.py, webview/platforms/mshtml.py, webview/platforms/qt.py, webview/platforms/winforms.py, webview/util.py
- New webview.settings['IGNORE_SSL_ERRORS'] setting
- Fix QT open links in new window
- Make webview.settings immutable
=> Ignore ssl errors

webview/platforms/winforms.py
On the Windows platform, when the system theme changes, the title bar theme follows the system theme changes
=> [Winforms] Title bar theme follows system theme changes

appveyor.yml, pyproject.toml
This fixes pygobject to a previous version until it's fixed.
=> There's something bad about the latest pygobject packaging.

webview/platforms/cocoa.py
=> [Cocoa] Fix minimize+restore silently failing

webview/__init__.py, webview/js/customize.js, webview/util.py
=> Add `DRAG_REGION_DIRECT_TARGET_ONLY` setting

webview/js/customize.js
=> Handle new elements in draggable and drag region client logic
